<#
.SYNOPSIS
    清除 i18n.manifest 中指定 Module 的 ETag，強制 AutoGen 重新從 S3 下載最新翻譯。

.DESCRIPTION
    auto-gen 工具使用 ETag 避免重複下載 S3 資料。
    當翻譯 Key 在 ETag 快取建立後才被 Publish，工具會誤判「No Change」而跳過下載，
    導致 AutoGenerated 類別只有 XML 註解、沒有 public static string 屬性。

    執行此腳本清除 ETag 後，重新執行 Init Translation 即可解決。

.PARAMETER ManifestPath
    i18n.manifest 的完整路徑。
    預設值：src\Common\Nine1.Livebuy.Common.Translations\i18n\Nine1.Livebuy\i18n.manifest

.PARAMETER ModuleName
    要清除 ETag 的 Module 名稱，例如 "backend.general"。
    留空則清除 manifest 中所有 Module 的 ETag。

.EXAMPLE
    .\fix-etag-cache.ps1 -ModuleName "backend.general"

.EXAMPLE
    .\fix-etag-cache.ps1 -ManifestPath "src\Common\MyProject.Common.Translations\i18n\MyProject\i18n.manifest" -ModuleName "backend.service.product"
#>
param(
    [string] $ManifestPath = "src\Common\Nine1.Livebuy.Common.Translations\i18n\Nine1.Livebuy\i18n.manifest",

    [string] $ModuleName = ""
)

if (-not (Test-Path $ManifestPath)) {
    Write-Error "找不到 manifest 檔案：$ManifestPath"
    exit 1
}

$json = Get-Content $ManifestPath -Raw | ConvertFrom-Json

$targets = $json.PSObject.Properties
if ($ModuleName -ne "") {
    $targets = $targets | Where-Object { $_.Value.Module -eq $ModuleName }
    if (-not $targets) {
        Write-Error "找不到 Module：$ModuleName（請確認名稱正確）"
        exit 1
    }
}

$count = 0
$targets | ForEach-Object {
    $_.Value.ETag = ""
    $count++
}

$json | ConvertTo-Json -Depth 5 | Set-Content $ManifestPath -Encoding UTF8NoBOM

if ($ModuleName -ne "") {
    Write-Host "✅ 已清除 Module「$ModuleName」的 ETag（共 $count 筆）"
} else {
    Write-Host "✅ 已清除所有 Module 的 ETag（共 $count 筆）"
}

Write-Host ""
Write-Host "請重新執行："
Write-Host "  dotnet-cake translation.cake --target=`"Init Translation`""
