<#
.SYNOPSIS
    透過 TextTransform.exe 執行 T4 範本產生 AutoGenerated 翻譯類別。

.DESCRIPTION
    NineYi.Sms 等 .NET Framework 專案無法使用 dotnet-t4，
    因為專案 DLL 為 .NET Framework 編譯，在 dotnet-t4 的 .NET Core
    執行環境下無法正確載入 System.Runtime.Caching 等 Framework 依賴。
    必須使用跑在 .NET Framework 上的 TextTransform.exe。

.PARAMETER ProjectDir
    含 generate.tt 的 Translation 專案目錄路徑。

.PARAMETER Configuration
    Build 組態（Debug / Release），預設 Debug。

.EXAMPLE
    .\run-t4-generate.ps1 -ProjectDir "D:\Code\NineYi.Sms\CrossLayer\Translations"
#>
param(
    [Parameter(Mandatory)]
    [string] $ProjectDir,

    [string] $Configuration = "Debug"
)

# 依實際安裝路徑擇一，優先使用 Professional；若找不到改用 BuildTools
$candidates = @(
    "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\TextTransform.exe",
    "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\TextTransform.exe",
    "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\TextTransform.exe"
)

$textTransform = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1

if (-not $textTransform) {
    Write-Error "找不到 TextTransform.exe，請安裝 Visual Studio 2022 或 Build Tools。下載：https://aka.ms/vs/17/release/vs_BuildTools.exe"
    exit 1
}

$binDir  = Join-Path $ProjectDir "bin\$Configuration"
$ttFile  = Join-Path $ProjectDir "generate.tt"
$tempTt  = Join-Path $ProjectDir "generate.tmp.tt"

if (-not (Test-Path $ttFile)) {
    Write-Error "找不到 T4 範本：$ttFile"
    exit 1
}

if (-not (Test-Path $binDir)) {
    Write-Error "找不到 bin 目錄 $binDir，請先 Build 專案後再執行此腳本。"
    exit 1
}

try {
    # $(TargetDir) 是 MSBuild 變數，TextTransform.exe 不會自動解析，需預先替換
    $ttContent = Get-Content $ttFile -Raw
    $ttContent = $ttContent -replace '\$\(TargetDir\)', ($binDir.TrimEnd('\') + '\')
    Set-Content $tempTt $ttContent -Encoding UTF8

    Write-Host "執行 TextTransform.exe：$textTransform"
    & $textTransform $tempTt -out (Join-Path $ProjectDir "generate.txt")

    if ($LASTEXITCODE -ne 0) {
        Write-Error "TextTransform.exe 執行失敗（exit code: $LASTEXITCODE）"
        exit $LASTEXITCODE
    }

    Write-Host "✅ T4 產生完成，請確認 AutoGenerated/ 目錄下的 .cs 檔案時間戳已更新。"
}
finally {
    if (Test-Path $tempTt) { Remove-Item $tempTt }
}
