<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSwag.AspNetCore" Version="14.6.3" />
    <PackageReference Include="Nine1.BaseSDK.AspNetCore" Version="10.0.0" />
    <PackageReference Condition="'$(isDatabaseSecretNone)' != 'true'" Include="Nine1.BaseSDK.Extensions.Data.SecretProvider" Version="10.0.0" />
    <PackageReference Condition="'$(isDatabaseSecretPostgresql)' == 'true'" Include="Npgsql" Version="10.0.2" />
    <PackageReference Condition="'$(isDatabaseSecretMssql)' == 'true'" Include="Microsoft.Data.SqlClient" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(isFlatStruct)' == 'true'">
    <ProjectReference Include="..\Nine1.Sample.Project.BL.BE\Nine1.Sample.Project.BL.BE.csproj" />
    <ProjectReference Include="..\Nine1.Sample.Project.BL.Services\Nine1.Sample.Project.BL.Services.csproj" />
    <ProjectReference Include="..\Nine1.Sample.Project.Common.Utils\Nine1.Sample.Project.Common.Utils.csproj" />
    <ProjectReference Include="..\Nine1.Sample.Project.DA.DB\Nine1.Sample.Project.DA.DB.csproj" />
    <ProjectReference Include="..\Nine1.Sample.Project.DA.Repositories\Nine1.Sample.Project.DA.Repositories.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(isModuleStruct)' == 'true'">
    <ProjectReference Include="..\..\BusinessLogic\Nine1.Sample.Project.BL.BE\Nine1.Sample.Project.BL.BE.csproj" />
    <ProjectReference Include="..\..\BusinessLogic\Nine1.Sample.Project.BL.Services\Nine1.Sample.Project.BL.Services.csproj" />
    <ProjectReference Include="..\..\Common\Nine1.Sample.Project.Common.Utils\Nine1.Sample.Project.Common.Utils.csproj" />
    <ProjectReference Include="..\..\DataAccess\Nine1.Sample.Project.DA.DB\Nine1.Sample.Project.DA.DB.csproj" />
    <ProjectReference Include="..\..\DataAccess\Nine1.Sample.Project.DA.Repositories\Nine1.Sample.Project.DA.Repositories.csproj" />
  </ItemGroup>

</Project>
