<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Nine1.Sample.Project.BL.Services</AssemblyName>
    <RootNamespace>ForDeveloping-Nine1.Sample.Project.BL.Services</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nine1.Sample.Project.DA.DB\Nine1.Sample.Project.DA.DB.csproj" />
    <ProjectReference Include="..\Nine1.Sample.Project.DA.Repositories\ForDeveloping-Nine1.Sample.Project.DA.Repositories.csproj" />
    <ProjectReference Include="..\Nine1.Sample.Project.BL.BE\Nine1.Sample.Project.BL.BE.csproj" />
    <ProjectReference Include="..\Nine1.Sample.Project.Common.Utils\Nine1.Sample.Project.Common.Utils.csproj" />
  </ItemGroup>

</Project>
