name: local
variables:
  - name: base-url
    value: http://localhost:5000
  - name: scm_api
    value: https://api.91mai.com
  - name: shop_Id
    value: "10230"
  - name: token
    value: "85932145"
  - name: api_key
    value: 071311bf-c8ff-45a4-b907-c3887a31e1d6
  - name: salt_key
    value: 7d7d4add
  - name: phone
    value: "+886988542534"
  - name: request_id
    value: NY0643
  - name: machine_code
    value: NY0643
  - name: location_code
    value: "12314"
  - name: employee_code
    value: "00001"
  - name: outermembercode
    value: WEN0000128
  - name: member_code
    value: 70001899F1
  - name: timestamp
    value: "1765381050"
  - name: signature
    value: b706d90983d5d8bb63eafca8c92231871d2c090cbc7cab214654986090e06ac6d2b0a3d65a54e37180878e539d9a86148434a466feabf44698c5f66c6b2d4bff
  - name: request_body
    value: '{"OuterMemberCode":"WEN0000128","MemberCode":"70001899F1","CellPhone":"+6584787891"}'
  - name: usingChannelType
    value: fefef
