name: local
variables:
  - name: base-url
    value: http://api.dev.91dev.tw
  - name: token
    value: "85932145"
  - name: timestamp
    value: ""
  - name: signature
    value: ""
  - name: saltKey
    value: 7d7d4add
  - name: apiKey
    value: 071311bf-c8ff-45a4-b907-c3887a31e1d6
  - name: shopId
    value: "10230"
